### ISSUE TITLE
Allow configuring headers to look in for clientid, passkey

### ISSUE THREAD

**Issue by amalfra** [gojek-engineering/client-authenticator-rb#3]
It might be better if the header to look for clientid & passkey are configurable. Right now it seems to be looking at hardcoded `client-id` & `pass-key`

**Comment by dineshkumar-cse** [comment]
Hi @amalfra, thanks for raising an issue.
configuring header keys feature is in pipeline will do it when i've time. I would be glad to merge if you can raise a PR.

**Comment by amalfra** [comment]
@dineshkumar-cse If you haven't already started working on it, I can actually use sometime this weekend

**Comment by dineshkumar-cse** [comment]
@amalfra sure go ahead.
